// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmygsppuicndlvsjjpdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJteWdzcHB1aWNuZGx2c2pqcGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzAzNjQsImV4cCI6MjA3MDU0NjM2NH0.Kxv49wDNdvYe0sQycWamzR-AACU-434hKQeRjm_v8-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});